"""Render deterministic native instructions without copying upstream packages."""

from __future__ import annotations

import argparse
import json
import os
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMANDS = (
    "spec",
    "plan",
    "build",
    "test",
    "constraints",
    "review",
    "webperf",
    "code-simplify",
    "ship",
)
PERSONAS = ("code-reviewer", "security-auditor", "test-engineer", "web-performance-auditor")
RULES = ("engineering", "agent-skills", "context7", "gh-stack")
HEADER = "<!-- Generated by scripts/render.py; edit shared source or adapters. -->\n\n"


def artifact_directory(worktree: Path) -> Path:
    """Select this worktree's artifacts; reject ambiguous legacy/new state."""
    slug = worktree.resolve().name
    current = worktree / ".harness/work" / slug
    legacy = worktree / ".claude/specs" / slug
    active = [path for path in (current, legacy) if path.exists() and any(path.iterdir())]
    if len(active) == 2:
        raise ValueError("Conflicting current and legacy process artifacts")
    return active[0] if active else current


def build_auto_spec(worktree: Path) -> Path:
    """Require the selected worktree's explicit spec before autonomous build."""
    spec = artifact_directory(worktree) / "spec.md"
    if not spec.is_file():
        raise ValueError("Run spec first: this worktree has no spec.md")
    return spec


def _text(root: Path, name: str) -> str:
    return (root / name).read_text().rstrip() + "\n"


def _upstream(resource: str) -> str:
    return (
        "Resolve the single enabled `agent-skills` plugin through the native plugin registry "
        "and verify its revision against harness's dependencies.lock.toml. Read "
        f"`{resource}` from that complete installed package, then execute its instructions "
        "and referenced skills/resources. Do not copy or patch upstream content. If the "
        "package, resource, or revision cannot be verified, stop and report the missing "
        "native dependency. Reject duplicate-name registrations rather than shadowing them. "
        "Apply the shared agent-skills overrides to all upstream paths and approvals.\n"
    )


def outputs(root: Path) -> tuple[dict[Path, str], dict[Path, str]]:
    """Compute native files and relative links entirely from tracked source inputs."""
    files: dict[Path, str] = {}
    links: dict[Path, str] = {}
    repository = HEADER + _text(root, "repository/instructions.md")
    files[Path("AGENTS.md")] = repository
    files[Path("CLAUDE.md")] = repository
    for client, filename in (("claude", "CLAUDE.md"), ("codex", "AGENTS.md")):
        rules = RULES if client == "codex" else ("engineering",)
        files[Path(f"generated/{client}/{filename}")] = (
            HEADER
            + "\n".join(_text(root, f"rules/{rule}.md") for rule in rules)
            + "\n"
            + _text(root, f"adapters/{client}/instructions.md")
        )
        for name in ("shepherd", "reflect"):
            package = Path(f"generated/{client}/skills/{name}")
            content = _text(root, f"skills/{name}/SKILL.md")
            if client == "codex":
                content = content.replace("disable-model-invocation: true\n", "")
            files[package / "SKILL.md"] = content
            for helper in sorted((root / f"skills/{name}").iterdir()):
                if helper.name != "SKILL.md" and not helper.name.startswith("."):
                    links[package / helper.name] = os.path.relpath(helper, root / package)
            if name == "reflect":
                if client == "codex":
                    files[package / "agents/openai.yaml"] = (
                        "policy:\n  allow_implicit_invocation: false\n"
                    )
                local = Path(f"{'.agents' if client == 'codex' else '.claude'}/skills/reflect")
                links[local] = os.path.relpath(root / package, root / local.parent)
    for name in COMMANDS:
        files[Path(f"generated/codex/skills/{name}/SKILL.md")] = (
            f"---\nname: {name}\ndescription: Run the {name} development lifecycle workflow "
            "using the installed agent-skills plugin.\n---\n\n"
            + _upstream(f".claude/commands/{name}.md")
            + "\nPass the user's arguments as the command's `$ARGUMENTS`. Resolve process "
            "artifacts only in this worktree's selected `.harness/work/<slug>/` or legacy "
            "`.claude/specs/<slug>/`; stop on conflicting locations. Honor prior authorization. "
            "Never commit process artifacts. Human review and merge remain mandatory.\n"
            + (
                "\nFor auto/all mode require this worktree's spec.md; default mode completes "
                "one task. Use the shared build-auto clean-baseline and completion contract.\n"
                if name == "build"
                else ""
            )
            + (
                "\nUse native subagents named code-reviewer, security-auditor, test-engineer "
                "in parallel when available. Otherwise read their upstream prompts and run "
                "sequentially, explicitly reporting fallback. Publication may ready the PR; "
                "invoke shepherd in the same turn and report actual monitoring status.\n"
                if name == "ship"
                else ""
            )
        )
    for name in PERSONAS:
        files[Path(f"generated/codex/agents/{name}.toml")] = (
            f'name = "{name}"\ndescription = "Run the upstream {name} research/review persona."\n'
            'sandbox_mode = "read-only"\n'
            + "developer_instructions = "
            + json.dumps(
                _upstream(f"agents/{name}.md")
                + "Research/review only; do not edit project files. Return the original "
                "persona's structured report, evidence, severity, and explicit gaps. "
                "Do not delegate from this persona. Verify effective read-only permissions."
            )
            + "\n"
        )
    shared = _text(root, "agents/docs-researcher.md")
    data = tomllib.loads(_text(root, "dependencies.lock.toml"))
    version = data["context7"]["version"]
    if not isinstance(version, str) or not version or version == "latest":
        raise ValueError("Context7 requires a reviewed exact version")
    shared = shared.replace("{context7_version}", version)
    claude = json.loads(_text(root, "adapters/claude/docs-researcher.json"))
    files[Path("generated/claude/agents/docs-researcher.md")] = (
        "---\n"
        + "".join(f"{key}: {json.dumps(value)}\n" for key, value in claude.items())
        + "---\n\n"
        + shared
    )
    files[Path("generated/codex/agents/docs-researcher.toml")] = (
        _text(root, "adapters/codex/docs-researcher.toml")
        + "developer_instructions = "
        + json.dumps(shared)
        + "\n"
    )
    return files, links


def render(root: Path = ROOT, *, check: bool = False) -> list[str]:
    """Write generated files, or report drift without mutating anything in check mode."""
    files, links = outputs(root)
    drift: list[str] = []
    expected = set(files) | set(links)
    generated = root / "generated"
    if generated.exists():
        for directory, dirs, names in os.walk(generated, followlinks=False):
            base = Path(directory)
            names += [name for name in dirs if (base / name).is_symlink()]
            for name in names:
                relative = (base / name).relative_to(root)
                if relative not in expected:
                    drift.append(str(relative))
                    if not check:
                        (root / relative).unlink()
    for relative, content in files.items():
        target = root / relative
        if target.is_file() and not target.is_symlink() and target.read_text() == content:
            continue
        drift.append(str(relative))
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.is_symlink():
                target.unlink()
            target.write_text(content)
    for relative, source in links.items():
        target = root / relative
        if target.is_symlink() and os.readlink(target) == source:
            continue
        drift.append(str(relative))
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.exists() or target.is_symlink():
                raise ValueError(f"Refusing to replace non-generated link collision: {target}")
            target.symlink_to(source)
    return drift


def main() -> int:
    """Return nonzero when check mode finds stale committed generation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift = render(check=args.check)
    if args.check and drift:
        print("Generated output drift:\n" + "\n".join(drift))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
